### ISSUE TITLE
wrong link TYPE_SYMFONY_VIOLATIONS = 'https://symfony.com/errors/validation';

### ISSUE THREAD

**Issue by NickSun** [phpro/api-problem#10]
ValidationApiProblem::TYPE_SYMFONY_VIOLATIONS = 'https://symfony.com/errors/validation' leads to the 404 page.

**Comment by Landerstraeten** [comment]
@veewee, Should it be: `https://symfony.com/doc/5.0/validation.html#constraints` ?

**Comment by veewee** [comment]
Took it from the official symfony repo:
https://github.com/symfony/serializer/blob/master/Normalizer/ConstraintViolationListNormalizer.php#L67

Maybe better to log an issue there and make the url accessible again?

**Comment by veewee** [comment]
Feel free to reopen if we should change it according to the Symfony Contributors.
